version: "3.8"

services:
  # 1. O Broker de mensagens MQTT (Mosquitto)
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker_atr
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    network_mode: "host"

  # 2. O Processo do Robô Embarcado (C++)
  robot-app:
    build: ./robot-cpp
    container_name: robo_embarcado_cpp
    depends_on:
      - mqtt-broker
    network_mode: "host"
    restart: on-failure

  # 3. O Processo do Simulador + Interface Gráfica Nativa (Pygame)
  simulation-app:
    build: ./simulation-remote
    container_name: simulador_interface_python
    depends_on:
      - mqtt-broker
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1 # Desativa compartilhamento de memória MIT-SHM (Culpado pela tela preta)
      - LIBGL_ALWAYS_SOFTWARE=1 # Garante renderização estável via CPU no WSL
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ipc: host # Permite que o contêiner converse direto com a memória gráfica do host
    network_mode: "host"
    restart: on-failure
