version: "3.8"

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker_atr
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - rede_inspecao

  robot-app:
    build: ./robot-cpp
    container_name: robo_embarcado_cpp
    depends_on:
      - mqtt-broker
    network_mode: "host"
    restart: on-failure

  simulation-app:
    build: ./simulation-remote
    container_name: simulador_interface_python
    depends_on:
      - mqtt-broker
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    restart: on-failure

networks:
  rede_inspecao:
    driver: bridge
